/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

const InfoRow = ({ label, value }) => (
  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow text-base font-semibold leading-6 text-neutral-600 max-md:max-w-full">
        <div className="justify-center items-start py-4 pr-1 pl-4 bg-white border border-solid border-neutral-500 border-opacity-30 max-md:pr-5 max-md:max-w-full">
          {label}
        </div>
      </div>
    </div>
    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow text-base leading-6 text-neutral-400 max-md:max-w-full">
        <div className="justify-center items-start py-4 pr-1 pl-4 bg-white border-t border-r border-b border-solid border-neutral-500 border-opacity-30 max-md:pr-5 max-md:max-w-full">
          {value}
        </div>
      </div>
    </div>
  </div>
);

const TransactionRow = ({ date, description, amount, balance }) => (
  <tr>
    <td className="py-4 pr-1 pl-4 border-r border-b border-solid border-neutral-500 border-opacity-30">
      {date}
    </td>
    <td className="py-4 pr-1 pl-4 border-r border-b border-solid border-neutral-500 border-opacity-30">
      {description}
    </td>
    <td className="py-4 pr-1 pl-4 border-r border-b border-solid border-neutral-500 border-opacity-30">
      {amount}
    </td>
    <td className="py-4 pr-1 pl-4 border-r border-b border-solid border-neutral-500 border-opacity-30">
      {balance}
    </td>
  </tr>
);

function CustomerStatement() {
  const [customerReference, setCustomerReference] = React.useState("");
  const [exportClicked, setExportClicked] = React.useState(false);

  const customerInfo = [
    { label: "Customer Name", value: "Juma John" },
    { label: "Customer Reference", value: "456789123" },
    { label: "Service Address", value: "45 Nile Avenue, Juba" },
    { label: "Statement Date", value: "August 1, 2024" },
  ];

  const statementSummary = [
    { label: "Previous Balance", value: "SSP 10,000" },
    { label: "Payments Received", value: "SSP 5,000" },
    { label: "Current Charges", value: "SSP 9,500" },
    { label: "Total Amount Due", value: "SSP 14,500" },
  ];

  const transactionHistory = [
    {
      date: "07/01/2024",
      description: "Previous Balance",
      amount: "",
      balance: "SSP 10,000",
    },
    {
      date: "07/05/2024",
      description: "Payment Received",
      amount: "-SSP 5,000",
      balance: "SSP 5,000",
    },
    {
      date: "07/15/2024",
      description: "Water Usage Charge",
      amount: "SSP 7,500",
      balance: "SSP 12,500",
    },
    {
      date: "07/15/2024",
      description: "Service Charge",
      amount: "SSP 1,500",
      balance: "SSP 14,000",
    },
    {
      date: "07/15/2024",
      description: "Other Charges",
      amount: "SSP 500",
      balance: "SSP 14,500",
    },
  ];

  const handleCustomerReferenceClick = () => {
    setCustomerReference("456789123");
  };

  const handleExportClick = () => {
    setExportClicked(true);
    setTimeout(() => setExportClicked(false), 2000);
  };

  return (
    <main className="flex flex-col p-6 bg-white rounded-3xl max-md:px-5">
      <header className="flex gap-2 justify-between w-full text-base leading-6 max-md:flex-wrap max-md:max-w-full">
        <button
          onClick={handleCustomerReferenceClick}
          className="flex gap-2 py-3 pr-6 pl-4 rounded-3xl border border-solid border-neutral-500 border-opacity-10 text-neutral-400"
        >
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1b883934e776764e105e8e46f1475acd58c00a88d8117d4528bc796e3f67ab00?apiKey=2b51dad425e04206847488420121dc35&"
            className="shrink-0 self-start w-6 aspect-square"
            alt=""
          />
          <div>{customerReference || "Customer Reference"}</div>
        </button>
        <button
          onClick={handleExportClick}
          className={`flex gap-2 px-6 py-3 font-semibold text-white whitespace-nowrap rounded-3xl ${
            exportClicked ? "bg-green-500" : "bg-slate-500"
          } max-md:px-5`}
        >
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2db10bbbfea74ab4d6421f41550d261f3b0fc63c181014f826d06ba56fed8a5c?apiKey=2b51dad425e04206847488420121dc35&"
            className="shrink-0 self-start w-6 aspect-square"
            alt=""
          />
          <span>{exportClicked ? "Exported!" : "Export"}</span>
        </button>
      </header>

      <section className="mt-8 text-2xl font-semibold leading-10 text-neutral-600 max-md:max-w-full">
        Customer Information
      </section>
      <div className="mt-4 max-md:max-w-full">
        {customerInfo.map((item, index) => (
          <InfoRow key={index} label={item.label} value={item.value} />
        ))}
      </div>

      <section className="mt-8 text-2xl font-semibold leading-10 text-neutral-600 max-md:max-w-full">
        Statement Summary
      </section>
      <div className="mt-4 max-md:max-w-full">
        {statementSummary.map((item, index) => (
          <InfoRow key={index} label={item.label} value={item.value} />
        ))}
      </div>

      <section className="mt-8 text-2xl font-semibold leading-10 text-neutral-600 max-md:max-w-full">
        Transaction History
      </section>
      <div className="mt-4 max-md:max-w-full">
        <table className="w-full border-collapse">
          <thead>
            <tr>
              <th className="py-4 pr-1 pl-4 font-semibold bg-white border border-solid border-neutral-500 border-opacity-30 text-neutral-600 text-left">
                Date
              </th>
              <th className="py-4 pr-1 pl-4 font-semibold bg-white border border-solid border-neutral-500 border-opacity-30 text-neutral-600 text-left">
                Description
              </th>
              <th className="py-4 pr-1 pl-4 font-semibold bg-white border border-solid border-neutral-500 border-opacity-30 text-neutral-600 text-left">
                Amount
              </th>
              <th className="py-4 pr-1 pl-4 font-semibold bg-white border border-solid border-neutral-500 border-opacity-30 text-neutral-600 text-left">
                Balance
              </th>
            </tr>
          </thead>
          <tbody>
            {transactionHistory.map((transaction, index) => (
              <TransactionRow key={index} {...transaction} />
            ))}
          </tbody>
        </table>
      </div>
    </main>
  );
}

export default CustomerStatement;
